services:
  vote:
    image: localhost:5000/vote:v0
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./vote:/usr/local/app
    ports:
      - "5002:80"
    networks:
      - humansbestfriend-network

  result:
    image: localhost:5000/result:v0
    build: ./result
    entrypoint: ["nodemon", "--inspect=0.0.0.0", "server.js"]
    depends_on:
      - db
    volumes:
      - ./result:/usr/local/app
    ports:
      - "5001:80"
      - "127.0.0.1:9229:9229"
    networks:
      - humansbestfriend-network

  worker:
    image: localhost:5000/worker:v0
    build:
      context: ./worker
    depends_on:
      - redis
      - db
    networks:
      - humansbestfriend-network
